[workspace]
members = [
    "artinchip-rt",
    "artinchip-hal",
    "aicfwc",
    "examples/pbp/pbp-blinky",
    "examples/pbp/pbp-hello-world",
    "examples/pbp/pbp-i2c-master",
    "examples/pbp/pbp-boot-info",
    "examples/pbp/pbp-flash",
    "examples/pbp/pbp-dma",
    "examples/pbp/pbp-pwm",
    "examples/pbp/pbp-psram",
    "examples/pbp/pbp-common",
    "examples/pbp/pbp-async-uart",
    "examples/app/app-bootloader",
    "examples/app/app-blinky",
]
resolver = "3"
