//! Reads the app image manifest and forwards addresses to the build.
//!
//! Everything address-related lives in `app-bootloader.toml` (single source of
//! truth, no shell environment variable): `load_address` → `--defsym=APP_BASE`
//! for the app linker script, and `[[partition]]` → the generated on-flash layout
//! used at runtime (`storage::FLASH_LAYOUT` / `storage::PARTITION_TABLE`).
//!
//! The partition table is *ours*, not the vendor `partition.json` layout.

use std::{env, fmt::Write as _, fs, path::Path};

use aicfwc::app_img::{ComponentKind, ImageManifest};

const DEFAULT_APP_BASE: u32 = 0x406c_0000;

/// Used when the manifest declares no `[[partition]]` entries. The first
/// partition must stay at offset 0: BootROM reads the first-stage image there.
const DEFAULT_LAYOUT: &[(&str, u32, u32)] = &[
    ("bootloader", 0x0000_0000, 0x0008_0000), // 512 KiB: PBP + bootloader
    ("app", 0x0008_0000, 0x0040_0000),        // 4 MiB: application image
    ("data", 0x0048_0000, 0x0010_0000),       // 1 MiB: runtime data
];

fn main() {
    println!("cargo:rustc-link-arg=-Tartinchip-rt.ld");
    println!("cargo:rerun-if-changed=app-bootloader.toml");

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let manifest_path = Path::new(&manifest_dir).join("app-bootloader.toml");
    let manifest = ImageManifest::load(&manifest_path).ok();

    let base = manifest
        .as_ref()
        .and_then(|manifest| {
            manifest
                .components
                .iter()
                .find(|component| component.kind == ComponentKind::App)
                .and_then(|app| app.load_address)
        })
        .or_else(|| {
            env::var("ARTINCHIP_APP_BASE")
                .ok()
                .and_then(|v| parse_addr(&v))
        })
        .unwrap_or(DEFAULT_APP_BASE);
    println!("cargo:rustc-link-arg=--defsym=APP_BASE={base:#x}");

    let layout: Vec<(String, u32, u32)> = match manifest.as_ref() {
        Some(manifest) if !manifest.partitions.is_empty() => manifest
            .partitions
            .iter()
            .map(|p| (p.name.clone(), p.offset, p.size))
            .collect(),
        _ => DEFAULT_LAYOUT
            .iter()
            .map(|(name, offset, size)| ((*name).to_string(), *offset, *size))
            .collect(),
    };

    let out_dir = env::var("OUT_DIR").unwrap();
    let boot_app = manifest
        .as_ref()
        .map(|manifest| manifest.boot_app.clone())
        .unwrap_or_default();
    fs::write(
        Path::new(&out_dir).join("partitions.rs"),
        generate(&layout, &boot_app),
    )
    .expect("failed to write generated partition table");
}

/// Emit the `storage.rs` fragment holding the layout and the reported table.
fn generate(layout: &[(String, u32, u32)], boot_app: &str) -> String {
    let mut out = String::from(
        "// @generated by build.rs from app-bootloader.toml -- do not edit.\n\
         /// On-flash layout declared by `[[partition]]` in `app-bootloader.toml`.\n\
         pub const FLASH_LAYOUT: &[Partition] = &[\n",
    );
    for (name, offset, size) in layout {
        let _ = writeln!(
            out,
            "    Partition {{ name: {name:?}, offset: {offset:#x}, size: {size:#x} }},"
        );
    }
    out.push_str("];\n\n");

    // Human-readable form for `GET_PARTITION_TABLE`
    // (`mtd=spi0.0:512k(bootloader),4m(app),1m(data)`), matching the vendor shape.
    let mut table = String::from("mtd=spi0.0:");
    for (index, (name, _, size)) in layout.iter().enumerate() {
        if index > 0 {
            table.push(',');
        }
        let _ = write!(table, "{}({name})", human_size(*size));
    }
    let _ = writeln!(out, "/// Partition table string reported to the host.");
    let _ = writeln!(out, "pub const PARTITION_TABLE: &str = {table:?};");

    // App the bootloader jumps to on a normal (non-upgrade) start.
    let _ = writeln!(
        out,
        "\n/// App name a normal boot jumps to (`[image] app`); empty boots any valid\n\
         /// image in the `app` partition.\n\
         pub const BOOT_APP: &str = {boot_app:?};"
    );
    out
}

fn human_size(bytes: u32) -> String {
    if bytes.is_multiple_of(1024 * 1024) {
        format!("{}m", bytes / (1024 * 1024))
    } else if bytes.is_multiple_of(1024) {
        format!("{}k", bytes / 1024)
    } else {
        bytes.to_string()
    }
}

fn parse_addr(value: &str) -> Option<u32> {
    let value = value.trim();
    if let Some(hex) = value
        .strip_prefix("0x")
        .or_else(|| value.strip_prefix("0X"))
    {
        u32::from_str_radix(hex, 16).ok()
    } else {
        value.parse().ok()
    }
}
