//! SPI-NOR backend for the upgrade protocol.
//!
//! The protocol engine and `NorStorage` live in
//! `artinchip_hal::usbdrd`; the board-specific part is the
//! [`NorFlash`] implementation, which pairs the `W25QXXXJV` driver with its delay
//! source. `FLASH_LAYOUT` / `PARTITION_TABLE` come from `build.rs` and are the
//! `[[partition]]` layout, not the vendor `partition.json`.

use artinchip_hal::usbdrd::{NorError, NorFlash, Partition};
use embedded_hal::delay::DelayNs;
use embedded_hal::digital::OutputPin;
use embedded_hal::spi::SpiBus;
use w25qxxxjv::W25QXXXJV;

// Our own on-flash layout, generated by `build.rs` from the `[[partition]]`
// entries in `app-bootloader.toml`.
include!(concat!(env!("OUT_DIR"), "/partitions.rs"));

/// Adapter that pairs a [`W25QXXXJV`] with its delay source.
///
/// The driver uses its `manual_delay` feature, so every erase/program needs an
/// explicit [`DelayNs`]; keeping one here lets `NorStorage` stay delay-agnostic.
pub struct NorFlashDelay<SPI: SpiBus, CS: OutputPin, D: DelayNs> {
    flash: W25QXXXJV<SPI, CS>,
    delay: D,
}

impl<SPI: SpiBus, CS: OutputPin, D: DelayNs> NorFlashDelay<SPI, CS, D> {
    /// Wrap `flash`, driving its internal delays with `delay`.
    pub fn new(flash: W25QXXXJV<SPI, CS>, delay: D) -> Self {
        Self { flash, delay }
    }
}

impl<SPI: SpiBus, CS: OutputPin, D: DelayNs> NorFlash for NorFlashDelay<SPI, CS, D> {
    fn read(&mut self, addr: u32, buf: &mut [u8]) -> Result<(), NorError> {
        self.flash.read_data(addr, buf).map_err(|_| NorError)
    }

    fn erase_sector(&mut self, addr: u32) -> Result<(), NorError> {
        self.flash
            .erase_sector(addr, &mut self.delay)
            .map_err(|_| NorError)
    }

    fn program_sector(&mut self, addr: u32, data: &[u8]) -> Result<(), NorError> {
        // The driver erases the covering sectors before programming, so this is
        // only used with exactly one full, sector-aligned buffer.
        self.flash
            .write_program(addr, data, &mut self.delay)
            .map_err(|_| NorError)
    }
}
